# Generated by Django 5.1.7 on 2025-03-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='additionl_infor',
            new_name='additional_infor',
        ),
    ]
