# Generated by Django 5.1.7 on 2025-03-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rent_date',
            field=models.DateField(blank=True, help_text='actuel retrun date', null=True),
        ),
    ]
